# This Dockerfile builds the API only.

FROM python:3.8-slim-buster
WORKDIR /app

COPY api/requirements.txt api/api.py api/.flaskenv ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

COPY ./api /app

EXPOSE 5000
ENTRYPOINT ["./apiEntrypoint.sh"]